name: Matrix

on: push

jobs:
  example-matrix:
    strategy:
      matrix:
        node_version: [12, 14]
        os: [ubuntu-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

